import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ONIX_PLAYER_DIR = resolve(process.cwd(), 'lib/onix-player');
const REGISTRY_PATH = resolve(ONIX_PLAYER_DIR, 'players/index.ts');
const EXAMPLES_PAGE = resolve(process.cwd(), 'app/examples/page.tsx');

const EXCLUDED_FILES = new Set([
  'player-template.ts',
]);

export function discoverContentModules(): string[] {
  return readdirSync(ONIX_PLAYER_DIR)
    .filter((name) => name.endsWith('-content.ts') && !EXCLUDED_FILES.has(name))
    .map((name) => name.replace(/-content\.ts$/, ''))
    .sort();
}

function discoverExampleSlugsFromWebsite(): string[] {
  if (!existsSync(EXAMPLES_PAGE)) return [];
  const source = readFileSync(EXAMPLES_PAGE, 'utf8');
  const slugs = new Set<string>();
  for (const match of source.matchAll(/href:\s*["']\/examples\/([a-z0-9-]+)["']/g)) {
    slugs.add(match[1]);
  }
  return [...slugs].sort();
}

export function generatePlayersRegistry(options?: { warnMissing?: boolean }) {
  const slugs = discoverContentModules();
  const imports = slugs
    .map((slug) => `import { websitePlayer as ${slug} } from '../${slug}-content';`)
    .join('\n');
  const entries = slugs.map((slug) => `  ${slug},`).join('\n');

  const output = `/**
 * AUTO-GENERATED by lib/onix-player/generate-players-registry.ts
 * Do not edit manually. Add lib/onix-player/<slug>-content.ts exporting websitePlayer.
 */
${imports}
import type { WebsitePlayerDefinition } from '../types';

export const WEBSITE_PLAYERS_RAW: WebsitePlayerDefinition[] = [
${entries}
];
`;

  writeFileSync(REGISTRY_PATH, output, 'utf8');

  if (options?.warnMissing !== false) {
    const websiteSlugs = discoverExampleSlugsFromWebsite();
    const missing = websiteSlugs.filter((slug) => !slugs.includes(slug));
    if (missing.length > 0) {
      console.warn(
        `Examples on /examples without lib/onix-player/*-content.ts: ${missing.join(', ')}`
      );
    }
  }

  return { slugs, registryPath: REGISTRY_PATH };
}
